name = "ido-test"
main = "src/index.js"
compatibility_date = "2025-01-01"

# Rules for importing HTML and CSS as text
[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[rules]]
type = "Text"
globs = ["**/*.css"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*.svg"]