name = "applift-maintenance"
main = "src/worker.js"
compatibility_date = "2025-11-10"

[vars]
LIVE_SITE = "https://www.applift.co"
DEV_ACCESS_KEY = "applift_on_maintenance"

[site]
bucket = "./public"
